### ISSUE TITLE
Kindly check

### ISSUE THREAD

**Issue by imurreflection** [holisticdioxide/uwc-repo#1]
Hey mate, thank you for bringing this add-on to life. It was, it is and will always be best add-on.

May I request you to please fix hcclips and more importantly sexix. This is the only site providing some good quality Japanese adult entertainment. Thanks in advance and keep up the great work

**Comment by holisticdioxide** [comment]
Hey,

It seems that sexix is dead, and will probably be removed from the addon. Hclips will be fixed in the next version.

**Comment by imurreflection** [comment]
Thank you mate

On 08-Feb-2018 03:40, "holisticdioxide" <notifications@github.com> wrote:

Hey,

It seems that sexix is dead, and will probably be removed from the addon.
Hclips will be fixed in the next version.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/holisticdioxide/uwc-repo/issues/1#issuecomment-363928051>,
or mute the thread
