### ISSUE TITLE
Site Addition

### ISSUE THREAD

**Issue by imurreflection** [holisticdioxide/uwc-repo#2]
Hey Mate, thanks for the great job and for those new addition. You ate doing awesome job. May I also request you to look into adding datoporn.com. This is one of the best site with excellent quality. However, addition is on completely your discretion.

Keep up the great job!!!

**Comment by holisticdioxide** [comment]
Hey,

Added in [this commit](https://github.com/holisticdioxide/Ultimate-Whitecream/commit/39dc54540887c5ea1f554a6a93288f91e170c7dc)

**Comment by imurreflection** [comment]
Thanks a lot mate.. You are a star
