### ISSUE TITLE
Organization for Favorites

### ISSUE THREAD

**Issue by TarkusLV** [holisticdioxide/uwc-repo#3]
First, thanks for taking over this great addon!

It would be nice to have even a simple way to organize Favorites.  When you add an item to Favorites, if it's already there, it moves it to the end (by deleting the original first).  It would be nice to have that functionality within the Favorites themselves.  In fact, I've made a special build to do just that.  Unfortunately (not being a programmer at all), I can't figure a way to add that to the context menu while still retaining the ability to delete an item from Favorites.  I've only been able to figure out how to have one or the other, so I actually use two builds to organize, one for deleting and one for moving to the end of the list.

If there's any way you could add an additional context menu item for moving an item to the end of the list, it would be most appreciated.  I use Favorites a lot (primarily for webcam models), and without any organization, a large list can become a bit of a mess with no sense of order.

Thanks again!

**Comment by holisticdioxide** [comment]
Hi,

It is possible, I will try to implement it into the next version.

**Comment by holisticdioxide** [comment]
Added in [this commit](https://github.com/holisticdioxide/Ultimate-Whitecream/commit/4f32648f5b9cb45adc0534e27a1ecedfb93a5c56)

**Comment by TarkusLV** [comment]
Thank you so much, holisticdioxide!

**Comment by TarkusLV** [comment]
Been using the new code and it's awesome!  Only change I made was to comment out both refresh lines, because it's easier to bulk edit without them.  But that's a personal preference, and no big deal.

Thanks again!
