### ISSUE TITLE
Change Position Please.

### ISSUE THREAD

**Issue by imurreflection** [holisticdioxide/uwc-repo#4]
Hey mate, thanks for listening to us. This is highly appreciated. One request please if we can change the position of 'add keywords' in ' search" option. Actually, 'add keywords' and ' clear list' ' they both are one after other and accidentally user can click ' clear list' as I did myself multiple times due to incorrect and fast movement of cursor. Unfortunately, as there is no warning like ' do you wish to delete all keywords' prompt, all my keywords were deleted and I had to manually add 100+ keywords. Even if this is done or not, I sincerely appreciate your efforts in reviving this add-on. If there is any assistance ever required like testing etc, please do let me know

**Comment by holisticdioxide** [comment]
Hey,

I tried to address everything you wrote:

- Moving 'add keywords' and 'clear list' further apart - 'clear list' is now accessible from the addon settings (and clearing favorites button is also added)
- Adding a warning when clearing the list - this was actually implemented, so I don't know why it was not working for you before
- Having to add everything manually in case something bad happens - I added options to backup your keywords and also your favorites, and the option to restore them from the backup file. Now, if you back them up before modifying them, you can easily restore them without having to add them one by one manually. Restoring does not create duplicates.

Related [commit](https://github.com/holisticdioxide/Ultimate-Whitecream/commit/8e68ab41602a851008d4bf9d261cd80a76261bd3)

And regarding testing, you can always use the latest development version from the git repository and report anything that is broken. It helps a lot, thank you.

**Comment by imurreflection** [comment]
Hey Bro, many thanks for this..this was much needed. Could you please provide me link for the development version on GitHub and i will be happy to test and report any bug to you..once thanks for addressing this. Have a nice day

**Comment by holisticdioxide** [comment]
[This repository](https://github.com/holisticdioxide/Ultimate-Whitecream) contains the most current code. To use it, download the content of the repository and place the plugin.video.uwc directory in a zip file (not the content of the directory, but the directory), then you can install the addon from that zip.

**Comment by imurreflection** [comment]
Bro, please explain a little more..like I download master.zip and then
extract the content and copy video plugin for uwc and then zip it back and
then install in Kodi..is this correct procedure? Sorry for bugging you too
much with this. I think I should wait for 1.1.62 update rather.please advise

**Comment by imurreflection** [comment]
Please ignore..I managed to do it..I will report any bug to you from 1.1.62 version..thanks again mate
